run_name: 'omniglot'

data:
  data_name: 'omniglot'
  num_clusters_data: 5 
  path: 'datasets/omniglot'

training:
  num_epochs: 150
  num_epochs_smalltree: 150
  num_epochs_intermediate_fulltrain: 80
  num_epochs_finetuning: 200
  batch_size: 256
  lr: 0.001
  weight_decay: 0.00001
  decay_lr: 0.1
  decay_stepsize: 100
  decay_kl: 0.001
  kl_start: 0.001

  inp_shape: 784
  latent_dim: [8, 8, 8, 8, 8, 8]
  mlp_layers: [128, 128, 128, 128, 128, 128] 
  initial_depth: 1
  activation: "sigmoid"
  encoder: 'cnn_omni' 
  grow: True
  prune: True
  num_clusters_tree: 5
  compute_ll: False
  augment: True
  augmentation_method: 'simple' 
  aug_decisions_weight: 1


globals:
  wandb_logging: 'online' 
  eager_mode: True
  seed: 42
  save_model: False
  config_name: 'omniglot'